update scripts - added logging and other changes

diff --git a/scripts/get_logs b/scripts/get_logs
--- a/scripts/get_logs
+++ b/scripts/get_logs
@@ -1,21 +1,27 @@
 #!/bin/bash
 
+if [[ -z  $OHRM_DIR ]]; then
+    printf "\nPlease run this script from the OrangeHRM command\n"
+    printf "i.e. orangehrm backup\n\n"
+    exit 1;
+fi
+
 now=$(date +"%Y_%m_%d_%H_%M_%S")
 containerLogDir="/var/www/html/src/log"
-localLogDir="${HOME}/orangehrm_logs/${now}"
+localLogDir="$HOME/orangehrm_logs/$now"
 
-echo -e "\nThis command will retrieve logs from the OrangeHRM container and store them at ${HOME}/orangehrm_logs\n"
+printf "\nThis command will retrieve logs from the OrangeHRM container and store them at %s/orangehrm_logs\n\n" "$HOME"
 
-mkdir -p "${localLogDir}"
+mkdir -p "$localLogDir"
 
-echo -e "${YELLOW}Copying logs${ENDCOLOR}......................${WIP_ICON}"
-docker cp orangehrm:"${containerLogDir}" "${localLogDir}" --quiet
-tput cuu1
-echo -e "${GREEN}Copying logs${ENDCOLOR}......................${SUCCESS_ICON}\n"
+print_progress_message "Copying logs" wip
+docker cp orangehrm:"$containerLogDir" "$localLogDir/ohrm_logs" --quiet
+cp -r "$OHRM_DIR/logs" "$localLogDir/command_logs"
+print_progress_message "Copying logs" success rewrite
 
-echo -e "Your logs are available at ${localLogDir}\n"
+printf "Your logs are available at %s\n\n" "${localLogDir}"
 
-echo -e "If you want to transfer them to your local machine, you can try the following commmand on your local machine:"
+printf "If you want to transfer them to your local machine, you can try the following commmand on your local machine:\n"
 token=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
 ohrmIP=$(curl -s -H "X-aws-ec2-metadata-token: ${token}" http://169.254.169.254/latest/meta-data/public-ipv4)
-echo -e "'${GREEN}scp -i your_identity_file -r ${USER}@${ohrmIP}:${localLogDir} your_local_path${ENDCOLOR}'\n"
+printf "'%bscp -i your_identity_file -r %s@%s:%s your_local_path%b'\n\n" "$GC" "$USER" "$ohrmIP" "$localLogDir" "$EC"
